### ISSUE TITLE
是否會支援big5uao 呀?

### ISSUE THREAD

**Issue by tentenlee100** [Truth0906/PTTCrawlerLibrary#1]
因為有要發文用日文的需求，所以需要用的日文來發文，需要使用到big5uao編碼。

這是之前有研究發文的時候用的到的相關程式但是它是2.7的

https://gist.github.com/NEJmark/add42a5d812e2909c7aee24a42b23836/revisions

**Comment by Truth0906** [comment]
好的，沒問題，列入更新清單。

**Comment by Truth0906** [comment]
已經支援囉!! 並更新字元表至新版本。
用日文發文測試OK!
