### ISSUE TITLE
使用pythonw.exe無法跑

### ISSUE THREAD

**Issue by tentenlee100** [Truth0906/PTTCrawlerLibrary#2]
開發時用pythone.exe正常的在跑，但是想要用在背景執行的pythonw.exe跑的時候就沒有反應了。

python版本 3.6.2
os: windows 10
使用功能流程: 登入(不覆蓋重複登入)->到test板po文就結束了

**Comment by Truth0906** [comment]
好，我除錯一下，會儘快回覆您。

**Comment by Truth0906** [comment]
所有功能皆以經過 pythonw.exe 測試通過，感謝你的回報。
